<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pennington" Version="0.1.3" />
    <PackageReference Include="Pennington.ApiMetadata.Reflection" Version="0.1.3" />
    <PackageReference Include="Pennington.MonorailCss" Version="0.1.3" />
    <PackageReference Include="Pennington.UI" Version="0.1.3" />
    <PackageReference Include="Pennington.TreeSitter" Version="0.1.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Spectre.Console" Version="0.57.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="1.0.0-alpha.0.11" />
    <PackageReference Include="Spectre.Console.ImageSharp" Version="0.57.0" />
    <PackageReference Include="Spectre.Console.Json" Version="0.57.0" />
  </ItemGroup>
</Project>